// GENERATED by scripts/generate-usage-presentation.mjs. DO NOT EDIT.
// SSOT: shared/src/usage-presentation.ts
#pragma once
#include <cstring>
#include <cctype>
namespace UsagePresentation {
static constexpr const char* Heading = "USAGE";
static constexpr const char* Providers[] = {"Claude","Codex","z.ai","Antigravity"};
inline bool lunaActive(float primary, float secondary, float reserve) { return reserve >= 0 && (primary >= 100 || secondary >= 100); }
inline bool startsWith(const char* name, const char* prefix) {
    while (*name == ' ') ++name;
    while (*prefix) { if (std::tolower(static_cast<unsigned char>(*name++)) != std::tolower(static_cast<unsigned char>(*prefix++))) return false; }
    return true;
}
inline int subscriptionProvider(const char* name) {
    if (startsWith(name, "Claude")) return 0;
    if (startsWith(name, "ChatGPT") || startsWith(name, "Codex")) return 1;
    if (startsWith(name, "GLM Coding Plan") || startsWith(name, "z.ai")) return 2;
    if (startsWith(name, "Google AI") || startsWith(name, "Antigravity") || startsWith(name, "AGY")) return 3;
    return -1;
}
}
